services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "node1"
      ENABLE_MODULES: "backup-filesystem"
      BACKUP_FILESYSTEM_PATH: "/backups"
      AUTOSCHEMA_ENABLED: "false"
    volumes:
      - weaviate_data:/var/lib/weaviate
      - ./backups/weaviate:/backups
    restart: unless-stopped

  chroma:
    image: chromadb/chroma
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/data
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/data
    restart: unless-stopped

  pgvector:
    image: ankane/pgvector
    container_name: pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vectors
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  qdrant_data:
    name: qdrant_data
  weaviate_data:
    name: weaviate_data
  chroma_data:
    name: chroma_data
  pgvector_data:
    name: pgvector_data
